FROM debian:12

ENV PIP_BREAK_SYSTEM_PACKAGES 1
ENV CMAKE_GENERATOR=Ninja

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install \
      sudo \
      git \
      build-essential \
      tar curl wget zip unzip gnupg2 \
      cmake \
      ninja-build \
      python3-pip \
      python3-venv \
      python-is-python3 \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/doganulus/cudd.git /tmp/cudd \
&& cd /tmp/cudd \
&& ./configure && aclocal && autoconf \
&& ./configure --enable-silent-rules --enable-shared --enable-obj \
&& make && make install \
&& cd / && rm -rf /tmp/cudd


RUN mkdir /test

COPY test/* /test/
